project:
  type: website

website:
  title: "my-website"
  navbar:
    right:
      - blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/aateg

  page-footer: 
    center: 
      - "Copyright 2023, aateg" 

format:
  html:
    theme: cosmo
    css: static/styles.css
    page-layout: full



