project:
  type: website

website:
  title: "aateg"
  favicon: "static/sun.png"
  navbar:
    logo: static/sun.png
    right:
      - text: "About"
        href: about.qmd
      - icon: medium
        href: https://medium.com/@aateg29
      - icon: github
        href: https://github.com/aateg

  page-footer: 
    center: 
      - "Copyright 2023, aateg" 
  
  search: false

format:
  html:
    theme: cosmo
    css: static/styles.css
    page-layout: full
